version: "3.8"
services:
  kaspersky-feeds-for-opencti:
    build: .
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=70f0e135-2558-4fbd-a858-f1dbcc7fac3b
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Kaspersky Feeds
      - CONNECTOR_SCOPE=kaspersky
      - CONNECTOR_CONFIDENCE_LEVEL=100
      - CONNECTOR_LOG_LEVEL=info
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_EXPOSE_METRICS=false
      - KASPERSKY_API_ROOT=https://taxii.tip.kaspersky.com/v2/
      - KASPERSKY_API_TOKEN=sYTNi5MkTQ6H2MB4b28jLA==
      - KASPERSKY_INITIAL_HISTORY=604800 # 7 days in seconds
      - KASPERSKY_UPDATE_INTERVAL=3600 # 1 hour in seconds
    restart: always
